#!/bin/bash
# Update FUG stories with detailed documentation

API_KEY="plane_api_efb329a1bef9492995648b9ee92e939a"
PROJECT_ID="f110c685-ede4-4756-8e41-8cb39bb316f3"
BASE_URL="http://localhost:8088/api/v1/workspaces/fug/projects/$PROJECT_ID"

update_issue() {
    local issue_id="$1"
    local description="$2"

    curl -s -X PATCH -H "x-api-key: $API_KEY" -H "Content-Type: application/json" \
      -d "{\"description_html\": \"$description\"}" \
      "$BASE_URL/issues/$issue_id/" > /dev/null

    echo "Updated $issue_id"
}

echo "=== Updating stories with detailed documentation ==="

# US-001
update_issue "52c8703f-b4db-490a-9471-5407d365b082" "<h2>US-001: Inscription par email</h2><h3>Critères d'acceptation</h3><ul><li>✅ Formulaire: email, mot de passe, confirmation</li><li>✅ Validation: min 8 caractères, 1 majuscule, 1 chiffre</li><li>⚠️ Email de vérification (URL callback à configurer)</li><li>✅ Message erreur si email existe</li><li>✅ Redirection vers création profil</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/auth/data/auth_repository.dart</code> - signUp()</li><li><code>lib/features/auth/presentation/register_screen.dart</code></li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Formulaire complet avec validation temps réel</li><li>Gestion erreurs Appwrite avec messages FR</li><li>State management Riverpod</li></ul><h3>À faire</h3><ul><li>Configurer URL callback email vérification</li><li>Tests unitaires</li></ul>"

# US-002
update_issue "4d1eb4f6-9419-4f61-a563-19ac22eadbfe" "<h2>US-002: Inscription OAuth</h2><h3>Critères d'acceptation</h3><ul><li>⚠️ Bouton Google fonctionnel</li><li>⚠️ Bouton Apple fonctionnel (obligatoire iOS)</li><li>⚠️ Récupération email et photo</li><li>⚠️ Création compte lié OAuth</li><li>⚠️ Gestion erreurs OAuth</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/auth/presentation/login_screen.dart</code> - UI boutons présents</li><li><code>lib/features/auth/data/auth_repository.dart</code> - stubs signInWithGoogle/Apple</li></ul><p><strong>État:</strong> UI présente mais backend non implémenté</p><h3>À faire</h3><ul><li>Configurer projet Google Cloud Console</li><li>Configurer Apple Developer pour Sign in with Apple</li><li>Implémenter signInWithGoogle() dans AuthRepository</li><li>Implémenter signInWithApple() dans AuthRepository</li><li>Tests</li></ul>"

# US-003
update_issue "48fffc30-3398-4503-84a3-5504af55fc6a" "<h2>US-003: Connexion utilisateur</h2><h3>Critères d'acceptation</h3><ul><li>✅ Formulaire email/mot de passe</li><li>✅ Option Se souvenir de moi</li><li>⚠️ Connexion OAuth (dépend US-002)</li><li>✅ Message erreur identifiants incorrects</li><li>✅ Redirection accueil après connexion</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/auth/data/auth_repository.dart</code> - signIn()</li><li><code>lib/features/auth/presentation/login_screen.dart</code></li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Login email/password complet</li><li>Session persistante via Appwrite</li><li>Gestion états loading/error</li><li>Navigation vers home après succès</li></ul>"

# US-004
update_issue "b2c6168b-2125-494c-95e6-2c64f666f641" "<h2>US-004: Réinitialisation mot de passe</h2><h3>Critères d'acceptation</h3><ul><li>✅ Lien Mot de passe oublié sur login</li><li>✅ Envoi email avec lien (valide 1h)</li><li>⚠️ Formulaire nouveau mot de passe</li><li>✅ Confirmation visuelle</li><li>⚠️ Invalidation anciennes sessions</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/auth/data/auth_repository.dart</code> - recoverPassword(), confirmRecovery()</li><li><code>lib/features/auth/presentation/login_screen.dart</code> - dialog récupération</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Dialog email pour reset</li><li>Appel Appwrite createRecovery()</li><li>Toast confirmation envoi</li></ul>"

# US-005
update_issue "f90bc476-422d-4733-92a8-798724532fb9" "<h2>US-005: Déconnexion</h2><h3>Critères d'acceptation</h3><ul><li>✅ Bouton accessible dans paramètres</li><li>✅ Confirmation avant déconnexion</li><li>✅ Suppression token local</li><li>✅ Redirection vers login</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/auth/data/auth_repository.dart</code> - signOut()</li><li><code>lib/features/profile/presentation/profile_screen.dart</code> - bouton logout</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Appel Appwrite deleteSession()</li><li>Clear state Riverpod</li><li>Navigation GoRouter vers /login</li></ul>"

# US-006
update_issue "6051e157-97d6-47c0-a43a-76009d12fe5e" "<h2>US-006: Suppression de compte</h2><h3>Critères d'acceptation</h3><ul><li>❌ Option dans paramètres compte</li><li>❌ Double confirmation + mot de passe</li><li>❌ Info données supprimées</li><li>❌ Délai grâce 30 jours</li><li>❌ Email confirmation</li><li>❌ Possibilité annuler pendant délai</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Non implémenté</p><h3>À faire</h3><ul><li>Créer écran confirmation suppression</li><li>Implémenter soft delete avec délai 30j</li><li>Ajouter fonction Appwrite pour suppression différée</li><li>Email notification suppression planifiée</li><li>Endpoint annulation suppression</li><li>RGPD: documenter données supprimées</li></ul>"

# US-007
update_issue "e0b470a3-e8f4-4c32-b979-a8efc8264680" "<h2>US-007: Création profil initial</h2><h3>Critères d'acceptation</h3><ul><li>✅ Pseudo unique</li><li>✅ Date de naissance</li><li>✅ Ville</li><li>✅ Upload photo (optionnel)</li><li>✅ Sélection boissons préférées</li><li>✅ Bio courte (max 150 car)</li><li>✅ Validation et sauvegarde</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/auth/domain/user_model.dart</code> - UserModel complet</li><li><code>lib/features/profile/data/profile_repository.dart</code> - createProfile()</li><li><code>lib/features/profile/presentation/edit_profile_screen.dart</code></li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Modèle avec 15+ propriétés</li><li>Validation pseudo unique via query</li><li>Upload avatar vers Appwrite Storage</li><li>Interests comme liste de strings</li></ul>"

# US-008
update_issue "034e99b0-0bbf-4ee7-a307-cf1c201ae25c" "<h2>US-008: Modification du profil</h2><h3>Critères d'acceptation</h3><ul><li>✅ Accès depuis page profil</li><li>✅ Modification tous champs sauf date naissance</li><li>✅ Preview avant sauvegarde</li><li>⚠️ Changement pseudo limité 1x/mois</li><li>✅ Validation temps réel</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/profile/presentation/edit_profile_screen.dart</code></li><li><code>lib/features/profile/data/profile_repository.dart</code> - updateProfile()</li><li><code>lib/features/profile/domain/profile_state.dart</code> - EditProfileNotifier</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Formulaire complet avec tous champs</li><li>StateNotifier pour gestion état dirty</li><li>Validation en temps réel</li></ul><h3>À faire</h3><ul><li>Implémenter limitation changement pseudo</li></ul>"

# US-009
update_issue "f0c82f10-8350-4411-ba1d-3f0853e75bd9" "<h2>US-009: Gestion photo de profil</h2><h3>Critères d'acceptation</h3><ul><li>✅ Upload depuis galerie ou camera</li><li>✅ Recadrage circulaire</li><li>✅ Compression (max 2MB)</li><li>✅ Formats: JPG, PNG</li><li>⚠️ Modération automatique</li><li>✅ Avatar par défaut si non fournie</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/profile/data/profile_repository.dart</code> - uploadAvatar(), deleteAvatar()</li><li><code>lib/features/profile/presentation/edit_profile_screen.dart</code> - ImagePicker</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>image_picker pour galerie/camera</li><li>Upload vers Appwrite Storage</li><li>Support web (bytes) et mobile (file)</li><li>Suppression ancienne image</li></ul><h3>À faire</h3><ul><li>Ajouter modération IA contenu</li></ul>"

# US-010
update_issue "aacea0f3-1a84-405f-ad4d-1645f0244c8b" "<h2>US-010: Préférences boissons</h2><h3>Critères d'acceptation</h3><ul><li>✅ Catégories: Bière, Vin, Cocktails, Soft, Café, Autre</li><li>✅ Sélection multiple</li><li>⚠️ Niveau (occasionnel, amateur, connaisseur)</li><li>⚠️ Option Je goûte tout</li><li>✅ Affichage sur profil public</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/auth/domain/user_model.dart</code> - interests: List&lt;String&gt;</li><li><code>lib/features/profile/presentation/edit_profile_screen.dart</code> - FilterChips</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>12 intérêts prédéfinis</li><li>Multi-select avec FilterChip</li><li>Affichage chips sur profil</li></ul><h3>À faire</h3><ul><li>Ajouter niveau expertise par catégorie</li></ul>"

# US-011
update_issue "dcecb159-b62b-4b3e-82b0-0b5b4b7bda66" "<h2>US-011: Visualisation profil public</h2><h3>Critères d'acceptation</h3><ul><li>✅ Bouton Voir mon profil public</li><li>✅ Affichage identique vue autres</li><li>✅ Indication éléments visibles/masqués</li><li>✅ Retour facile vers édition</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/profile/presentation/profile_screen.dart</code></li><li><code>lib/core/providers/auth_provider.dart</code> - currentUserProvider</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>ProfileScreen avec paramètre userId</li><li>Vue différente si isOwnProfile</li><li>Boutons Follow/Message si autre profil</li><li>Boutons Edit/Create FUG si own profil</li></ul>"

# US-012
update_issue "eac31cc9-77b0-4eab-b39a-70fb870e8d8a" "<h2>US-012: Recherche utilisateurs</h2><h3>Critères d'acceptation</h3><ul><li>✅ Barre recherche écran principal</li><li>✅ Recherche par pseudo (autocomplétion)</li><li>✅ Résultats: photo, pseudo, ville</li><li>⚠️ Filtres: ville, préférences</li><li>✅ Gestion cas sans résultat</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/social/data/social_repository.dart</code> - searchUsers()</li><li><code>lib/features/social/presentation/user_search_screen.dart</code></li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Query Appwrite avec search sur name</li><li>Exclude parameter pour filtrer</li><li>Liste résultats avec UserTile</li></ul>"

# US-013
update_issue "18712821-2c79-40aa-a079-3eecfe2d9ccc" "<h2>US-013: Suivre un utilisateur</h2><h3>Critères d'acceptation</h3><ul><li>✅ Bouton Suivre sur profil</li><li>✅ Confirmation visuelle (devient Suivi)</li><li>✅ Incrémentation compteur followers</li><li>⚠️ Notification à l'utilisateur suivi</li><li>✅ Liste personnes suivies</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/social/data/social_repository.dart</code> - follow(), isFollowing()</li><li><code>lib/features/profile/presentation/profile_screen.dart</code> - bouton Follow</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Collection followers dans Appwrite</li><li>FollowRelation model</li><li>Toggle follow/unfollow</li></ul><h3>À faire</h3><ul><li>Notification push au suivi</li></ul>"

# US-014
update_issue "97923d6d-d0ec-4b38-af2f-6388515a71bc" "<h2>US-014: Ne plus suivre</h2><h3>Critères d'acceptation</h3><ul><li>✅ Bouton Ne plus suivre</li><li>✅ Action immédiate sans confirmation</li><li>✅ Décrémentation compteur</li><li>✅ Pas de notification</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/social/data/social_repository.dart</code> - unfollow()</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Delete document follow relation</li><li>UI toggle instantané</li></ul>"

# US-015
update_issue "c4e29fbe-f064-4f55-9d8d-05e657ba546a" "<h2>US-015: Liste followers/abonnements</h2><h3>Critères d'acceptation</h3><ul><li>✅ Onglets Followers et Abonnements</li><li>✅ Liste avec photo, pseudo, bouton action</li><li>✅ Compteurs sur profil</li><li>✅ Follow/unfollow depuis liste</li><li>✅ Pagination scroll infini</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/social/data/social_repository.dart</code> - getFollowers(), getFollowing()</li><li><code>lib/features/social/presentation/followers_list_screen.dart</code></li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Queries avec pagination (limit/offset)</li><li>TabBar Followers/Following</li><li>UserTile avec bouton action</li></ul>"

# US-016
update_issue "38faa634-c5b1-43bc-b1df-abab9ed5ae28" "<h2>US-016: Bloquer utilisateur</h2><h3>Critères d'acceptation</h3><ul><li>✅ Option Bloquer dans menu profil</li><li>✅ Confirmation avant blocage</li><li>✅ Bloqué ne peut plus: voir profil, inviter, suivre</li><li>✅ Liste utilisateurs bloqués</li><li>✅ Possibilité débloquer</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/social/data/social_repository.dart</code> - blockUser(), unblockUser(), isBlocked(), getBlockedUsers()</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Collection blocks dans Appwrite</li><li>Vérification isBlocked avant actions</li><li>Liste bloqués dans paramètres</li></ul>"

# US-017
update_issue "c4b52efd-8909-4f20-a828-bbd18e397199" "<h2>US-017: Créer un FUG</h2><h3>Critères d'acceptation</h3><ul><li>✅ Formulaire: titre, description, date/heure, lieu, type boisson</li><li>✅ Sélection lieu via carte ou recherche</li><li>✅ Nombre max participants (2-20)</li><li>✅ Visibilité: Public/Followers/Invitation</li><li>✅ Preview avant publication</li><li>⚠️ Partage après création</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/events/presentation/create_event_screen.dart</code></li><li><code>lib/features/events/data/event_repository.dart</code> - createEvent()</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Stepper 4 étapes</li><li>Step 1: Info de base + image</li><li>Step 2: Date/heure avec pickers</li><li>Step 3: Location picker carte interactive</li><li>Step 4: Options (prix, max participants, tags)</li></ul>"

# US-018
update_issue "2eb50610-2e0d-4c1a-9e38-39e58130a82b" "<h2>US-018: Carte des FUG</h2><h3>Critères d'acceptation</h3><ul><li>✅ Carte interactive centrée sur position</li><li>✅ Permission géolocalisation</li><li>✅ Marqueurs par type</li><li>⚠️ Cluster si trop nombreux</li><li>✅ Tap marqueur = aperçu</li><li>✅ Filtres: date, type, distance</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/events/presentation/events_map_screen.dart</code></li><li><code>lib/features/events/data/event_repository.dart</code> - getNearbyEvents()</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>flutter_map + OpenStreetMap</li><li>Markers couleur: amber=featured, green=free, red=full</li><li>Search radius slider 1-50km</li><li>Bottom sheet preview événement</li><li>Filter sheet (radius, free only, available)</li><li>Haversine distance calculation</li></ul>"

# US-019
update_issue "34433037-07a1-4438-93c6-f41da4f2a010" "<h2>US-019: Détails d'un FUG</h2><h3>Critères d'acceptation</h3><ul><li>✅ Affichage: titre, description, date/heure, lieu</li><li>✅ Info organisateur (profil cliquable)</li><li>✅ Liste participants (profils cliquables)</li><li>✅ Places restantes</li><li>✅ Bouton action (Rejoindre/Demander/Complet)</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/events/presentation/event_detail_screen.dart</code></li><li><code>lib/features/events/domain/event_model.dart</code></li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>SliverAppBar avec image</li><li>Badges: featured, free, full, cancelled</li><li>Info card: date, durée, prix, participants</li><li>Mini-map avec bouton directions</li><li>Organisateur card cliquable</li><li>Tags section</li></ul>"

# US-020
update_issue "0f4114ec-aaee-492a-a346-52d9f922d143" "<h2>US-020: Rejoindre FUG public</h2><h3>Critères d'acceptation</h3><ul><li>⚠️ Bouton Rejoindre si places dispo</li><li>⚠️ Confirmation immédiate</li><li>⚠️ Ajout à Mes FUG</li><li>⚠️ Notification organisateur</li><li>⚠️ Mise à jour compteur</li></ul><h3>Implémentation</h3><p><strong>État:</strong> UI présente, backend TODO</p><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/events/presentation/event_detail_screen.dart</code> - bouton présent</li></ul><h3>À faire</h3><ul><li>Créer collection event_participants</li><li>Implémenter joinEvent() dans EventRepository</li><li>Créer fonction Appwrite join-event</li><li>Notification à l'organisateur</li><li>Incrémenter currentParticipants</li></ul>"

# US-021
update_issue "de6ed546-9365-44c2-a29b-9ec159f9230a" "<h2>US-021: Demander rejoindre FUG privé</h2><h3>Critères d'acceptation</h3><ul><li>❌ Bouton Demander à rejoindre</li><li>❌ Message optionnel</li><li>❌ Statut En attente visible</li><li>❌ Notification organisateur</li><li>❌ Possibilité annuler demande</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Non implémenté</p><h3>À faire</h3><ul><li>Ajouter status 'pending' dans event_participants</li><li>UI demande avec champ message</li><li>Notification push organisateur</li><li>Gestion annulation demande</li></ul>"

# US-022
update_issue "0ffe0005-edfe-4c4e-9a5a-b52552eadc3b" "<h2>US-022: Gérer demandes participation</h2><h3>Critères d'acceptation</h3><ul><li>❌ Liste demandes en attente</li><li>❌ Profil demandeur consultable</li><li>❌ Boutons Accepter/Refuser</li><li>❌ Notification au demandeur</li><li>❌ Historique demandes traitées</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Non implémenté</p><h3>À faire</h3><ul><li>Créer écran gestion demandes (organisateur)</li><li>Query demandes pending par event</li><li>Actions accept/reject</li><li>Notifications push décision</li></ul>"

# US-023
update_issue "c3372d2f-58fe-4d08-953d-8e612acde51d" "<h2>US-023: Inviter utilisateurs</h2><h3>Critères d'acceptation</h3><ul><li>❌ Sélection depuis followers/abonnements</li><li>❌ Recherche utilisateurs</li><li>❌ Envoi invitations multiples</li><li>❌ Notification aux invités</li><li>❌ Suivi invitations (acceptée, refusée, attente)</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Non implémenté</p><h3>À faire</h3><ul><li>Créer collection event_invitations</li><li>UI sélection multi-utilisateurs</li><li>Notifications push invitations</li><li>Gestion réponses invitations</li></ul>"

# US-024
update_issue "2649574a-2da8-4a5b-a887-08cdecc08565" "<h2>US-024: Annuler participation</h2><h3>Critères d'acceptation</h3><ul><li>❌ Bouton Annuler ma participation</li><li>❌ Confirmation avant annulation</li><li>❌ Notification organisateur</li><li>❌ Place libérée</li><li>❌ Retrait de Mes FUG</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Non implémenté</p><h3>À faire</h3><ul><li>Implémenter leaveEvent() dans EventRepository</li><li>Dialog confirmation</li><li>Notification organisateur</li><li>Décrémenter currentParticipants</li></ul>"

# US-025
update_issue "ae53398f-795e-4c30-bc46-fa407c206bbb" "<h2>US-025: Annuler FUG (organisateur)</h2><h3>Critères d'acceptation</h3><ul><li>⚠️ Bouton Annuler le FUG</li><li>❌ Motif obligatoire</li><li>⚠️ Confirmation avant annulation</li><li>❌ Notification tous participants</li><li>⚠️ FUG marqué Annulé</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/events/presentation/event_detail_screen.dart</code> - bouton TODO</li><li><code>lib/features/events/domain/event_model.dart</code> - status: cancelled</li></ul><h3>À faire</h3><ul><li>Dialog motif annulation</li><li>Implémenter cancelEvent()</li><li>Notifications push à tous participants</li></ul>"

# US-026
update_issue "7a526ce7-72a1-47c0-84b4-ef5272f6f20b" "<h2>US-026: Historique FUG</h2><h3>Critères d'acceptation</h3><ul><li>✅ Section Mes FUG</li><li>⚠️ Onglets Passés/À venir</li><li>✅ Tri par date</li><li>✅ Affichage: titre, date, lieu, participants</li><li>✅ Clic pour détails</li><li>⚠️ Indication rôle (organisateur/participant)</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/events/presentation/events_list_screen.dart</code></li><li><code>lib/features/events/data/event_repository.dart</code> - getEventsByOrganizer()</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Liste événements avec EventCard</li><li>Query par organizerId</li></ul><h3>À faire</h3><ul><li>Ajouter onglets Passés/À venir</li><li>Inclure événements où participant</li></ul>"

# US-027
update_issue "1598204e-4c27-463a-b2f4-f9322c0ff7b7" "<h2>US-027: Notifications push</h2><h3>Critères d'acceptation</h3><ul><li>❌ Permission au premier lancement</li><li>❌ Notifications: follower, invitation, demande</li><li>❌ Notifications: FUG modifié, annulé, rappel</li><li>❌ Tap = ouverture écran concerné</li><li>❌ iOS et Android</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Modèle OK, FCM/APNs non configuré</p><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/notifications/domain/notification_model.dart</code> - NotificationType enum</li></ul><h3>À faire</h3><ul><li>Configurer Firebase Cloud Messaging</li><li>Configurer APNs pour iOS</li><li>Créer fonction Appwrite send-notification</li><li>Implémenter firebase_messaging dans app</li><li>Deep links pour navigation</li></ul>"

# US-028
update_issue "a0a40d65-f01c-4e70-99d3-9bbf817c9268" "<h2>US-028: Centre notifications in-app</h2><h3>Critères d'acceptation</h3><ul><li>✅ Icône cloche avec badge</li><li>✅ Liste chronologique</li><li>✅ Distinction lu/non lu</li><li>✅ Marquer comme lu</li><li>✅ Actions rapides</li><li>✅ Pagination</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/notifications/data/notification_repository.dart</code></li><li><code>lib/features/notifications/presentation/notifications_screen.dart</code></li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Query notifications avec pagination</li><li>markAsRead(), markAllAsRead()</li><li>Dismissible swipe-to-delete</li><li>Badge unread count</li><li>Navigation on tap</li><li>Realtime subscription</li></ul>"

# US-029
update_issue "d9d39068-6f15-40ee-ab84-077778101e2a" "<h2>US-029: Paramètres notifications</h2><h3>Critères d'acceptation</h3><ul><li>❌ Page paramètres dédiée</li><li>❌ Toggle par type</li><li>❌ Désactivation globale push</li><li>❌ Paramétrage rappels</li><li>❌ Sauvegarde auto</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Non implémenté</p><h3>À faire</h3><ul><li>Créer écran NotificationSettingsScreen</li><li>Ajouter champs préférences dans UserModel</li><li>Switches par type de notification</li><li>Sync avec Appwrite</li></ul>"

# US-030
update_issue "f757db09-7599-4674-8d66-26d1b2de0108" "<h2>US-030: Rappel avant FUG</h2><h3>Critères d'acceptation</h3><ul><li>❌ Push 24h avant</li><li>❌ Push 1h avant</li><li>❌ Contenu: titre, heure, lieu + lien itinéraire</li><li>❌ Personnalisation délais</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Non implémenté</p><h3>À faire</h3><ul><li>Créer fonction Appwrite scheduled reminder</li><li>Cron job pour vérifier événements proches</li><li>Template notification avec deep link</li><li>Settings délais personnalisés</li></ul>"

# US-031
update_issue "ee61edd1-12ab-418c-97f3-7459b3fa9ef3" "<h2>US-031: Système de badges</h2><h3>Critères d'acceptation</h3><ul><li>⚠️ Badges débloqués auto selon critères</li><li>❌ Notification nouveau badge</li><li>⚠️ Affichage badges sur profil</li><li>⚠️ Catégories: Participation, Organisation, Social, Spéciaux</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Champs présents, pas de logique</p><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/auth/domain/user_model.dart</code> - badge field</li></ul><h3>À faire</h3><ul><li>Créer collection achievements</li><li>Créer collection user_achievements</li><li>Définir critères déblocage</li><li>Fonction Appwrite gamification</li><li>Créer AchievementsScreen</li></ul>"

# US-032
update_issue "194bf28e-62d1-4ac7-8c92-05f48a257445" "<h2>US-032: Statistiques personnelles</h2><h3>Critères d'acceptation</h3><ul><li>✅ Nombre FUG participés/organisés</li><li>✅ Nombre followers/abonnements</li><li>⚠️ Boisson la plus consommée</li><li>⚠️ Bar le plus fréquenté</li><li>⚠️ Graphique activité mensuelle</li><li>⚠️ Comparaison mois précédent</li></ul><h3>Implémentation</h3><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/profile/domain/profile_model.dart</code> - totalEventsCreated, totalEventsAttended</li><li><code>lib/features/profile/presentation/profile_screen.dart</code> - stats card</li></ul><p><strong>Fonctionnalités:</strong></p><ul><li>Compteurs basiques affichés</li><li>Level progress bar</li></ul><h3>À faire</h3><ul><li>Agrégation données boissons/lieux</li><li>Graphiques avec fl_chart</li></ul>"

# US-033
update_issue "a81804ae-adb0-4f0b-b92b-e1a00670486a" "<h2>US-033: Niveaux et progression</h2><h3>Critères d'acceptation</h3><ul><li>⚠️ Système XP</li><li>⚠️ XP: créer FUG +20, participer +10, follower +5</li><li>⚠️ Paliers niveaux thématiques</li><li>⚠️ Barre progression</li><li>⚠️ Avantages par niveau</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Champs présents, pas de calcul automatique</p><p><strong>Fichiers:</strong></p><ul><li><code>lib/features/auth/domain/user_model.dart</code> - points field</li><li><code>lib/features/profile/domain/profile_model.dart</code> - level, levelProgress computed</li></ul><h3>À faire</h3><ul><li>Fonction Appwrite gamification pour attribution XP</li><li>Triggers sur create event, join, follow</li><li>Définir paliers et noms</li><li>UI progression détaillée</li></ul>"

# US-034
update_issue "9bf98f1a-597e-413b-8593-eca24825934c" "<h2>US-034: Classement (Post-MVP)</h2><h3>Critères d'acceptation</h3><ul><li>❌ Classement hebdo/mensuel</li><li>❌ Top 10 visible</li><li>❌ Ma position affichée</li><li>❌ Critères: XP, FUG organisés, participations</li><li>❌ Filtrable par ville</li></ul><h3>Implémentation</h3><p><strong>État:</strong> Non implémenté - Post-MVP</p><h3>À faire (v2)</h3><ul><li>Créer LeaderboardScreen</li><li>Query agrégation par période</li><li>Filtres géographiques</li></ul>"

# QA Stories
update_issue "3c7cd482-492d-4415-8d54-bf07f050c768" "<h2>QA-001: Tests Auth Flow</h2><h3>Scope</h3><ul><li>Tests unitaires AuthRepository</li><li>Tests widgets LoginScreen</li><li>Tests widgets RegisterScreen</li><li>Tests intégration sign up/sign in</li><li>Mock Appwrite responses</li></ul><h3>Fichiers à tester</h3><ul><li><code>lib/features/auth/data/auth_repository.dart</code></li><li><code>lib/features/auth/presentation/login_screen.dart</code></li><li><code>lib/features/auth/presentation/register_screen.dart</code></li></ul><h3>Critères de validation</h3><ul><li>Coverage &gt; 80%</li><li>Tous cas erreur testés</li><li>Validation formulaires testée</li></ul>"

update_issue "1bcc96e8-84ee-4371-94a5-66dcbe11f984" "<h2>QA-002: Tests Profile</h2><h3>Scope</h3><ul><li>Tests unitaires ProfileRepository</li><li>Tests widgets ProfileScreen</li><li>Tests widgets EditProfileScreen</li><li>Tests upload avatar</li></ul><h3>Fichiers à tester</h3><ul><li><code>lib/features/profile/data/profile_repository.dart</code></li><li><code>lib/features/profile/presentation/profile_screen.dart</code></li><li><code>lib/features/profile/presentation/edit_profile_screen.dart</code></li></ul>"

update_issue "bbe85e0b-553a-4eac-89eb-cbb9915f2efd" "<h2>QA-003: Tests Social</h2><h3>Scope</h3><ul><li>Tests unitaires SocialRepository</li><li>Tests follow/unfollow</li><li>Tests block/unblock</li><li>Tests recherche utilisateurs</li></ul><h3>Fichiers à tester</h3><ul><li><code>lib/features/social/data/social_repository.dart</code></li><li><code>lib/features/social/presentation/user_search_screen.dart</code></li><li><code>lib/features/social/presentation/followers_list_screen.dart</code></li></ul>"

update_issue "5c22438f-0d40-417c-9aa6-c03898d00a54" "<h2>QA-004: Tests Events</h2><h3>Scope</h3><ul><li>Tests unitaires EventRepository</li><li>Tests création événement (4 étapes)</li><li>Tests carte et géolocalisation</li><li>Tests recherche nearby (Haversine)</li></ul><h3>Fichiers à tester</h3><ul><li><code>lib/features/events/data/event_repository.dart</code></li><li><code>lib/features/events/presentation/create_event_screen.dart</code></li><li><code>lib/features/events/presentation/events_map_screen.dart</code></li></ul><h3>Points critiques</h3><ul><li>Calcul distance Haversine</li><li>Bounding box calculation</li><li>Form validation 4 steps</li></ul>"

update_issue "a2d12fee-5e60-4bd3-a06a-f4b50ca2d762" "<h2>QA-005: Tests Notifications</h2><h3>Scope</h3><ul><li>Tests NotificationRepository</li><li>Tests NotificationsScreen</li><li>Tests mark as read</li></ul><h3>Fichiers à tester</h3><ul><li><code>lib/features/notifications/data/notification_repository.dart</code></li><li><code>lib/features/notifications/presentation/notifications_screen.dart</code></li></ul>"

update_issue "cea76a34-951e-40da-9365-26cd60c27ae6" "<h2>QA-006: Tests E2E</h2><h3>Parcours à tester</h3><ul><li>Inscription → Création profil → Home</li><li>Création FUG → Publication → Visible sur carte</li><li>Recherche user → Follow → Voir dans followers</li><li>Login → Voir notifications → Mark read</li></ul><h3>Outils</h3><ul><li>integration_test package</li><li>flutter_driver ou patrol</li></ul><h3>Environnement</h3><ul><li>Appwrite test instance</li><li>Données de test isolées</li></ul>"

echo ""
echo "=== All stories updated with detailed documentation ==="
